
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SheetProvider } from "@/providers/SheetProviders";
import StoreProvider from "@/providers/StoreProvider";
import { NextAuthProvider } from "@/providers/NextAuthProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <StoreProvider>
            <SheetProvider />
            <Toaster />
            {children}
          </StoreProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
